### ISSUE TITLE
CardMatch_html

### ISSUE THREAD

**Issue by proti9** [danb-dliflc/HS2TemplateUpdate#51]
Please update the template by checking text areas showing for both English and target language (e.g. Italian) to be applied a below css value. And, check with contents on the staging.

letter-spacing: 0px;

**Comment by sueykim** [comment]
created 'cardmatch_italian.css' and updated the "Headstart-Team\Staging_Html" folder. Also updated activityMap.js in the "Staging_Html" folder. Please check.

**Comment by proti9** [comment]
The css file is added into the repository. Thanks for checking it.
