### ISSUE TITLE
DragDrop_html

### ISSUE THREAD

**Issue by proti9** [danb-dliflc/HS2TemplateUpdate#8]
Please update by checking text areas showing Japanese to be applied below css values. And, check with contents on the staging.

font-size: 19px;
letter-spacing: 0px;

**Comment by sueykim** [comment]
I tried with above css values. They looked really weird. Let's talk tomorrow. Thanks. -Sue

**Comment by proti9** [comment]
The css file is added into the repository. When the feedback comes next time, it could be re-considered.
